### ISSUE TITLE
`getDate(date)` function doesn't work for 21st/22nd/23rd or 31st

### ISSUE THREAD

**Issue by dadambickford** [taterbase/fancy-timestamp#4]
I've got a working solution in jsbin here - http://jsbin.com/wiqifowila/1/edit?js,console,output

If you're cool with something like that I can submit a PR for you to review?

**Comment by dadambickford** [comment]
Or if somehow I was testing it wrong feel free to shut it down :smile:

**Comment by taterbase** [comment]
Nice catch, yes please send a PR :smiley:

**Comment by dadambickford** [comment]
So in testing this I found one other weird thing. again let me know if I'm testing or using this wrong.

test.js file:
```
var ts = require('./index.js');
var date1 = new Date('12/21/2016');
console.log(ts(date1));
```

and in terminal this is outputting:
```
1:00am on Tuesday the 12th of June, 48942
```

If I add `true` for the milliseconds parameter it outputs the proper:
```
12:00am on Wednesday the 21st of December, 2016
```

Assuming usage is correct, I think the millisecond conversion here:
```
if(!milliseconds)
    timestamp = (timestamp * 1000);
```
should be:
```
if(!milliseconds)
    timestamp = (new Date(timestamp).getTime());
```

Just the one line but if you prefer I can make it a separate issue/PR?

**Comment by dadambickford** [comment]
Actually after reading the docs more carefully it appears this wasn't created to accept dates like '12/15/2016' so I think I'm getting ahead of myself.

**Comment by dadambickford** [comment]
cool all working, pushing and submitting the PR.

```
var ts = require('./index.js');

var date1 = new Date('12/21/2016');
var date2 = new Date('12/22/2016');
var date3 = new Date('12/23/2016');
var date4 = new Date('12/31/2016');

console.log(ts(date1, true));  // > 12:00am on Wednesday the 21st of December, 2016
console.log(ts(date2, true));  // > 12:00am on Thursday the 22nd of December, 2016
console.log(ts(date3, true));  // > 12:00am on Friday the 23rd of December, 2016
console.log(ts(date4, true));  // > 12:00am on Saturday the 31st of December, 2016
```
